require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BlogUrlsController do

  # This should return the minimal set of attributes required to create a valid
  # BlogUrl. As you add validations to BlogUrl, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "blog_url" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BlogUrlsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all blog_urls as @blog_urls" do
      blog_url = BlogUrl.create! valid_attributes
      get :index, {}, valid_session
      assigns(:blog_urls).should eq([blog_url])
    end
  end

  describe "GET show" do
    it "assigns the requested blog_url as @blog_url" do
      blog_url = BlogUrl.create! valid_attributes
      get :show, {:id => blog_url.to_param}, valid_session
      assigns(:blog_url).should eq(blog_url)
    end
  end

  describe "GET new" do
    it "assigns a new blog_url as @blog_url" do
      get :new, {}, valid_session
      assigns(:blog_url).should be_a_new(BlogUrl)
    end
  end

  describe "GET edit" do
    it "assigns the requested blog_url as @blog_url" do
      blog_url = BlogUrl.create! valid_attributes
      get :edit, {:id => blog_url.to_param}, valid_session
      assigns(:blog_url).should eq(blog_url)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BlogUrl" do
        expect {
          post :create, {:blog_url => valid_attributes}, valid_session
        }.to change(BlogUrl, :count).by(1)
      end

      it "assigns a newly created blog_url as @blog_url" do
        post :create, {:blog_url => valid_attributes}, valid_session
        assigns(:blog_url).should be_a(BlogUrl)
        assigns(:blog_url).should be_persisted
      end

      it "redirects to the created blog_url" do
        post :create, {:blog_url => valid_attributes}, valid_session
        response.should redirect_to(BlogUrl.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved blog_url as @blog_url" do
        # Trigger the behavior that occurs when invalid params are submitted
        BlogUrl.any_instance.stub(:save).and_return(false)
        post :create, {:blog_url => { "blog_url" => "invalid value" }}, valid_session
        assigns(:blog_url).should be_a_new(BlogUrl)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BlogUrl.any_instance.stub(:save).and_return(false)
        post :create, {:blog_url => { "blog_url" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested blog_url" do
        blog_url = BlogUrl.create! valid_attributes
        # Assuming there are no other blog_urls in the database, this
        # specifies that the BlogUrl created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BlogUrl.any_instance.should_receive(:update_attributes).with({ "blog_url" => "MyString" })
        put :update, {:id => blog_url.to_param, :blog_url => { "blog_url" => "MyString" }}, valid_session
      end

      it "assigns the requested blog_url as @blog_url" do
        blog_url = BlogUrl.create! valid_attributes
        put :update, {:id => blog_url.to_param, :blog_url => valid_attributes}, valid_session
        assigns(:blog_url).should eq(blog_url)
      end

      it "redirects to the blog_url" do
        blog_url = BlogUrl.create! valid_attributes
        put :update, {:id => blog_url.to_param, :blog_url => valid_attributes}, valid_session
        response.should redirect_to(blog_url)
      end
    end

    describe "with invalid params" do
      it "assigns the blog_url as @blog_url" do
        blog_url = BlogUrl.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BlogUrl.any_instance.stub(:save).and_return(false)
        put :update, {:id => blog_url.to_param, :blog_url => { "blog_url" => "invalid value" }}, valid_session
        assigns(:blog_url).should eq(blog_url)
      end

      it "re-renders the 'edit' template" do
        blog_url = BlogUrl.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BlogUrl.any_instance.stub(:save).and_return(false)
        put :update, {:id => blog_url.to_param, :blog_url => { "blog_url" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested blog_url" do
      blog_url = BlogUrl.create! valid_attributes
      expect {
        delete :destroy, {:id => blog_url.to_param}, valid_session
      }.to change(BlogUrl, :count).by(-1)
    end

    it "redirects to the blog_urls list" do
      blog_url = BlogUrl.create! valid_attributes
      delete :destroy, {:id => blog_url.to_param}, valid_session
      response.should redirect_to(blog_urls_url)
    end
  end

end
