require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GithubsController do

  # This should return the minimal set of attributes required to create a valid
  # Github. As you add validations to Github, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "github_url" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GithubsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all githubs as @githubs" do
      github = Github.create! valid_attributes
      get :index, {}, valid_session
      assigns(:githubs).should eq([github])
    end
  end

  describe "GET show" do
    it "assigns the requested github as @github" do
      github = Github.create! valid_attributes
      get :show, {:id => github.to_param}, valid_session
      assigns(:github).should eq(github)
    end
  end

  describe "GET new" do
    it "assigns a new github as @github" do
      get :new, {}, valid_session
      assigns(:github).should be_a_new(Github)
    end
  end

  describe "GET edit" do
    it "assigns the requested github as @github" do
      github = Github.create! valid_attributes
      get :edit, {:id => github.to_param}, valid_session
      assigns(:github).should eq(github)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Github" do
        expect {
          post :create, {:github => valid_attributes}, valid_session
        }.to change(Github, :count).by(1)
      end

      it "assigns a newly created github as @github" do
        post :create, {:github => valid_attributes}, valid_session
        assigns(:github).should be_a(Github)
        assigns(:github).should be_persisted
      end

      it "redirects to the created github" do
        post :create, {:github => valid_attributes}, valid_session
        response.should redirect_to(Github.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved github as @github" do
        # Trigger the behavior that occurs when invalid params are submitted
        Github.any_instance.stub(:save).and_return(false)
        post :create, {:github => { "github_url" => "invalid value" }}, valid_session
        assigns(:github).should be_a_new(Github)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Github.any_instance.stub(:save).and_return(false)
        post :create, {:github => { "github_url" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested github" do
        github = Github.create! valid_attributes
        # Assuming there are no other githubs in the database, this
        # specifies that the Github created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Github.any_instance.should_receive(:update_attributes).with({ "github_url" => "" })
        put :update, {:id => github.to_param, :github => { "github_url" => "" }}, valid_session
      end

      it "assigns the requested github as @github" do
        github = Github.create! valid_attributes
        put :update, {:id => github.to_param, :github => valid_attributes}, valid_session
        assigns(:github).should eq(github)
      end

      it "redirects to the github" do
        github = Github.create! valid_attributes
        put :update, {:id => github.to_param, :github => valid_attributes}, valid_session
        response.should redirect_to(github)
      end
    end

    describe "with invalid params" do
      it "assigns the github as @github" do
        github = Github.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Github.any_instance.stub(:save).and_return(false)
        put :update, {:id => github.to_param, :github => { "github_url" => "invalid value" }}, valid_session
        assigns(:github).should eq(github)
      end

      it "re-renders the 'edit' template" do
        github = Github.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Github.any_instance.stub(:save).and_return(false)
        put :update, {:id => github.to_param, :github => { "github_url" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested github" do
      github = Github.create! valid_attributes
      expect {
        delete :destroy, {:id => github.to_param}, valid_session
      }.to change(Github, :count).by(-1)
    end

    it "redirects to the githubs list" do
      github = Github.create! valid_attributes
      delete :destroy, {:id => github.to_param}, valid_session
      response.should redirect_to(githubs_url)
    end
  end

end
